
//
// Warning: don't edit - generated by generate_ecu_code.pl processing ../dev/sas_i1.json: SAS 22: Optional equipment system
// This generated code  makes it easier to process CANBUS messages from the SAS ecu in a BMW i3
//
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_LERNDATEN_RUECKSETZEN,                    {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0xABC9
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_VDC0_LESEN,                               {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0xD817
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_VDC0_LESEN_0XD817,                        {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0xD817
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_STATUS_SWC_VERSIONEN_LESEN_ANZAHL_DATENSAETZE,  {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0xDD33
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_READ_EXCEPTION_DATA,                      {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0x4001
  //{ I3_ECU_SAS_TX, I3_ECU_SAS_RX, VEHICLE_POLL_TYPE_OBDIIEXTENDED, I3_PID_SAS_CLEAR_EXCEPTION_DATA,                     {  0,  0,  0,  0 }, 0, ISOTP_EXTADR },   // 0xF000
