
//
// Warning: don't edit - generated by generate_ecu_code.pl processing ../dev/kafas20.json: KAF 5D: Camera based driver assistance system
// This generated code  makes it easier to process CANBUS messages from the KAF ecu in a BMW i3
//

#define I3_ECU_KAF_TX                                                0x06F15D
#define I3_ECU_KAF_RX                                                0x065DF1

// Skipping _BREMSENANSTEUERUNG_FCW on 0x4000 which takes arguments

#define I3_PID_KAF__FASTA_FLA_DATA                                   0x4001
        // _FASTA_FLA_DATA / _FASTA_FLA_DATA

    #define I3_RES_KAF_STAT_FLA_OP_TIME_WERT                         (RXBUF_UINT32(0))
    #define I3_RES_KAF_STAT_FLA_OP_TIME_WERT_UNIT                    's'
    #define I3_RES_KAF_STAT_FLA_OP_TIME_WERT_TYPE                    unsigned long
        // Duration of FLA activated by driver [s] / Zeitdauer FLA durch Fahrer aktiviert [s]

    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_NIGHT_WERT                (RXBUF_UINT32(4))
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_NIGHT_WERT_UNIT           's'
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_NIGHT_WERT_TYPE           unsigned long
        // Duration in the ambient brightness FLA activation allowed [s] / Zeitdauer in der Umgebungshelligkeit FLA
        // Aktivierung erlaubt  [s]

    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_HB_WERT               (RXBUF_UINT32(8))
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_HB_WERT_UNIT          's'
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_HB_WERT_TYPE          unsigned long
        // Duration of switch-on recommendation FLA [s] / Zeitdauer Einschaltempfehlung FLA  [s]

    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_LB_WERT               (RXBUF_UINT32(12))
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_LB_WERT_UNIT          's'
    #define I3_RES_KAF_STAT_DELTA_TIME_FLA_ACT_LB_WERT_TYPE          unsigned long
        // Duration of switch-off recommendation [s] / Zeitdauer Abschaltempfehlung [s]

    #define I3_RES_KAF_STAT_FLA_COUNT_OVERRIDE_WERT                  (RXBUF_UINT32(16))
    #define I3_RES_KAF_STAT_FLA_COUNT_OVERRIDE_WERT_UNIT             'Counts'
    #define I3_RES_KAF_STAT_FLA_COUNT_OVERRIDE_WERT_TYPE             unsigned long
        // Number of driver overloads / Anzahl Übersteuerung durch Fahrer

    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT                        (RXBUF_UINT32(20))
    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT_UNIT                   's'
    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT_TYPE                   unsigned long
        // Absolute operating time counter [s] / Absoluter Betriebszeitzähler [s]

#define I3_PID_KAF__KAFAS_ECU_DATA                                   0x4002
        // _KAFAS_ECU_DATA / _KAFAS_ECU_DATA

    #define I3_RES_KAF_STAT_CNTRY_CODE_WERT                          (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_CNTRY_CODE_WERT_UNIT                     'Counts'
    #define I3_RES_KAF_STAT_CNTRY_CODE_WERT_TYPE                     unsigned short
        // ISO Country Code of the country in which the vehicle covered the most kilometers. / ISO Country Code des
        // Landes in welchem das Fahrzeug die meisten  Kilometer zurückgelegt hat.

    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT_0X4002                 (RXBUF_UINT32(2))
    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT_0X4002_UNIT            's'
    #define I3_RES_KAF_STAT_OPTIME_TOTAL_WERT_0X4002_TYPE            unsigned long
        // Absolute operating time counter / Absoluter Betriebszeitzähler

    #define I3_RES_KAF_STAT_OPTIME_NIGHT_WERT                        (RXBUF_UINT32(6))
    #define I3_RES_KAF_STAT_OPTIME_NIGHT_WERT_UNIT                   's'
    #define I3_RES_KAF_STAT_OPTIME_NIGHT_WERT_TYPE                   unsigned long
        // Operating time at night. Based on BV-Algo overnight decision / Betriebszeit in der Nacht. Basiert auf BV-Algo
        // Nachtentscheidung

    #define I3_RES_KAF_STAT_OPTIME_WIPER_WERT                        (RXBUF_UINT32(10))
    #define I3_RES_KAF_STAT_OPTIME_WIPER_WERT_UNIT                   's'
    #define I3_RES_KAF_STAT_OPTIME_WIPER_WERT_TYPE                   unsigned long
        // Operating time during rain. Based on Algo Rain Decision / Betriebszeit während Regen. Basiert auf Algo
        // Regenentscheidung

    #define I3_RES_KAF_STAT_DRIVEN_DIST_TOTAL_WERT                   (RXBUF_UINT32(14))
    #define I3_RES_KAF_STAT_DRIVEN_DIST_TOTAL_WERT_UNIT              'km'
    #define I3_RES_KAF_STAT_DRIVEN_DIST_TOTAL_WERT_TYPE              unsigned long
        // Absolutely driven kilometers / Absolut gefahrene Kilometer

    #define I3_RES_KAF_STAT_DRIVEN_DIST_URBAN_WERT                   (RXBUF_UINT32(18))
    #define I3_RES_KAF_STAT_DRIVEN_DIST_URBAN_WERT_UNIT              'km'
    #define I3_RES_KAF_STAT_DRIVEN_DIST_URBAN_WERT_TYPE              unsigned long
        // Total kilometers driven on urban or residential area roads / Absolut gefahrene Kilometer auf Straßentyp Urban
        // oder Residential Area

    #define I3_RES_KAF_STAT_DRIVEN_DIST_RURAL_WERT                   (RXBUF_UINT32(22))
    #define I3_RES_KAF_STAT_DRIVEN_DIST_RURAL_WERT_UNIT              'km'
    #define I3_RES_KAF_STAT_DRIVEN_DIST_RURAL_WERT_TYPE              unsigned long
        // Absolute kilometers driven on the rural or highway type / Absolut gefahrene Kilometer auf Straßentyp Rural
        // oder Highway

    #define I3_RES_KAF_STAT_DRIVEN_DIST_MOWAY_WERT                   (RXBUF_UINT32(26))
    #define I3_RES_KAF_STAT_DRIVEN_DIST_MOWAY_WERT_UNIT              'km'
    #define I3_RES_KAF_STAT_DRIVEN_DIST_MOWAY_WERT_TYPE              unsigned long
        // Absolute kilometers driven on road type Motorway / Absolut gefahrene Kilometer auf Straßentyp Motorway

    #define I3_RES_KAF_STAT_DRIVEN_DIST_NA_WERT                      (RXBUF_UINT32(30))
    #define I3_RES_KAF_STAT_DRIVEN_DIST_NA_WERT_UNIT                 'km'
    #define I3_RES_KAF_STAT_DRIVEN_DIST_NA_WERT_TYPE                 unsigned long
        // Absolute kilometers driven with no available road type / Absolut gefahrene Kilometer ohne verfügbaren
        // Straßentyp

    #define I3_RES_KAF_STAT_AMNT_EYEQ_RESET_WERT                     (RXBUF_UINT(34))
    #define I3_RES_KAF_STAT_AMNT_EYEQ_RESET_WERT_UNIT                'Counts'
    #define I3_RES_KAF_STAT_AMNT_EYEQ_RESET_WERT_TYPE                unsigned short
        // Number of resets of the BV processor performed during normal operation / Anzahl der erfolgten Resets des
        // BV-Prozessors während normalem Betrieb

    #define I3_RES_KAF_STAT_AMNT_ONLINE_CALIB_WERT                   (RXBUF_UINT(36))
    #define I3_RES_KAF_STAT_AMNT_ONLINE_CALIB_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_AMNT_ONLINE_CALIB_WERT_TYPE              unsigned short
        // Counter for the completed online calibration processes / Zähler über die Erfolgten Online-Kalibriervorgänge

#define I3_PID_KAF__KAFAS_TLC_DATA                                   0x4003
        // _KAFAS_TLC_DATA / _KAFAS_TLC_DATA

    #define I3_RES_KAF_STAT_TLC_DRIV_LEFT_AVAIL_WERT                 (RXBUF_UINT32(0))
    #define I3_RES_KAF_STAT_TLC_DRIV_LEFT_AVAIL_WERT_UNIT            'km'
    #define I3_RES_KAF_STAT_TLC_DRIV_LEFT_AVAIL_WERT_TYPE            unsigned long
        // Absolute kilometers driven with availability on the left / Absolut gefahrene Kilometer mit Verfübarkeit auf
        // der linken Seite

    #define I3_RES_KAF_STAT_TLC_DRIV_RIGHT_AVAIL_WERT                (RXBUF_UINT32(4))
    #define I3_RES_KAF_STAT_TLC_DRIV_RIGHT_AVAIL_WERT_UNIT           'km'
    #define I3_RES_KAF_STAT_TLC_DRIV_RIGHT_AVAIL_WERT_TYPE           unsigned long
        // Absolute kilometers driven with availability on the right / Absolut gefahrene Kilometer mit Verfübarkeit auf
        // der rechten Seite

    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_REL_SPD_WERT               (RXBUF_UINT32(8))
    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_REL_SPD_WERT_UNIT          'km'
    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_REL_SPD_WERT_TYPE          unsigned long
        // Absolutely driven with active TLC and relevant speed / Absolut gefahrene  mit aktivem TLC und relavanter
        // Geschwindigkeit

    #define I3_RES_KAF_STAT_TLC_AMNT_WARN_WERT                       (RXBUF_UINT(12))
    #define I3_RES_KAF_STAT_TLC_AMNT_WARN_WERT_UNIT                  'Counts'
    #define I3_RES_KAF_STAT_TLC_AMNT_WARN_WERT_TYPE                  unsigned short
        // Number of issued TLC warnings / Anzahl ausgegebener TLC Warnungen

    #define I3_RES_KAF_STAT_TLC_AMNT_DEACT_WERT                      (RXBUF_UINT(14))
    #define I3_RES_KAF_STAT_TLC_AMNT_DEACT_WERT_UNIT                 'Counts'
    #define I3_RES_KAF_STAT_TLC_AMNT_DEACT_WERT_TYPE                 unsigned short
        // Number of times the TLC function was deactivated by the driver / Anzahl der Deaktivierung der TLC-Funktion
        // durch den Fahrer

    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_ACT_WERT                   (RXBUF_UINT32(16))
    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_ACT_WERT_UNIT              'km'
    #define I3_RES_KAF_STAT_TLC_DRIV_DIST_ACT_WERT_TYPE              unsigned long
        // Kilometers driven with activated TLC / Gefahrene Kilometer mit aktiviertem TLC

#define I3_PID_KAF_KAFAS_FCW_DATA                                    0x4004
        // KAFAS_FCW_DATA / KAFAS_FCW_DATA

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_ACT_WERT                 (RXBUF_UINT32(0))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_ACT_WERT_UNIT            'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_ACT_WERT_TYPE            unsigned long
        // Total kilometers driven with activated FCW function / Absolut gefahrene Kilometer mit aktivierter FCW Funktion

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_WERT                  (RXBUF_UINT32(4))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_WERT_UNIT             'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_WERT_TYPE             unsigned long
        // Total kilometers driven in fail safe mode / Absolut gefahrene Kilometer im Fail Safe Mode

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_ACT_WERT              (RXBUF_UINT32(8))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_ACT_WERT_UNIT         'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FS_ACT_WERT_TYPE         unsigned long
        // Total kilometers driven with activated FCW function in fail safe mode / Absolut gefahrene Kilometer mit
        // aktivierter FCW Funktion im Fail Safe Mode

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_OFF_WERT             (RXBUF_UINT32(12))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_OFF_WERT_UNIT        'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_OFF_WERT_TYPE        unsigned long
        // Absolutely driven kilometers with activated FCW function and advance warning level off / Absolut gefahrene
        // Kilometer mit aktivierter FCW Funktion und Vorwarnstufe  aus 

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_EARLY_WERT           (RXBUF_UINT32(16))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_EARLY_WERT_UNIT      'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_EARLY_WERT_TYPE      unsigned long
        // Total kilometers traveled with activated FCW function and early warning level / Absolut gefahrene Kilometer
        // mit aktivierter FCW Funktion und Vorwarnstufe  früh 

    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_LATE_WERT            (RXBUF_UINT32(20))
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_LATE_WERT_UNIT       'km'
    #define I3_RES_KAF_STAT_FCW_DRIVEN_DIST_FOR_LATE_WERT_TYPE       unsigned long
        // Total kilometers driven with activated FCW function and late warning level / Absolut gefahrene Kilometer mit
        // aktivierter FCW Funktion und Vorwarnstufe  spät 

    #define I3_RES_KAF_STAT_FCW_AMNT_FOR_WERT                        (RXBUF_UINT(24))
    #define I3_RES_KAF_STAT_FCW_AMNT_FOR_WERT_UNIT                   'Counts'
    #define I3_RES_KAF_STAT_FCW_AMNT_FOR_WERT_TYPE                   unsigned short
        // Number of pre-warnings / Anzahl der Vorwarnungen

    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_WERT                      (RXBUF_UINT(26))
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_WERT_UNIT                 'Counts'
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_WERT_TYPE                 unsigned short
        // Number of acute warnings / Anzahl der Akutwarnungen

    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_45_WERT                   (RXBUF_UINT(28))
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_45_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_45_WERT_TYPE              unsigned short
        // Number of acute warnings in the range 0 km / h¿ 45 km / h / Anzahl der Akutwarnungen im Bereich 0 km/h¿ 45
        // km/h

    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_90_WERT                   (RXBUF_UINT(30))
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_90_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_90_WERT_TYPE              unsigned short
        // Number of acute warnings in the range 45 km / h¿ 90 km / h / Anzahl der Akutwarnungen im Bereich 45 km/h¿ 90
        // km/h

    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_135_WERT                  (RXBUF_UINT(32))
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_135_WERT_UNIT             'Counts'
    #define I3_RES_KAF_STAT_FCW_AMNT_ACUTE_135_WERT_TYPE             unsigned short
        // Number of acute warnings in the range 90 km / h¿ 135 km / h / Anzahl der Akutwarnungen im Bereich 90 km/h¿ 135
        // km/h

    #define I3_RES_KAF_STAT_FCW_PREFILLS_WERT                        (RXBUF_UINT(34))
    #define I3_RES_KAF_STAT_FCW_PREFILLS_WERT_UNIT                   'Counts'
    #define I3_RES_KAF_STAT_FCW_PREFILLS_WERT_TYPE                   unsigned short
        // Number of pre-fill requests triggered by FCW / Anzahl der von FCW ausgelösten Pre-Fill Anforderungen

    #define I3_RES_KAF_STAT_FCW_PRECRASH_WERT                        (RXBUF_UINT(36))
    #define I3_RES_KAF_STAT_FCW_PRECRASH_WERT_UNIT                   'Counts'
    #define I3_RES_KAF_STAT_FCW_PRECRASH_WERT_TYPE                   unsigned short
        // Number of pre-crash messages triggered by FCW / Anzahl der von FCW ausgelösten Pre-Crash Meldungen

    #define I3_RES_KAF_STAT_FCW_DEACT_WERT                           (RXBUF_UINT(38))
    #define I3_RES_KAF_STAT_FCW_DEACT_WERT_UNIT                      'Counts'
    #define I3_RES_KAF_STAT_FCW_DEACT_WERT_TYPE                      unsigned short
        // Number of times the FCW function has been deactivated by the driver / Anzahl der Deaktivierung der
        // FCW-Funktion durch den Fahrer

    #define I3_RES_KAF_STAT_FCW_FS_CC_WERT                           (RXBUF_UINT(40))
    #define I3_RES_KAF_STAT_FCW_FS_CC_WERT_UNIT                      'Counts'
    #define I3_RES_KAF_STAT_FCW_FS_CC_WERT_TYPE                      unsigned short
        // Number of triggered Fail-Save CC messages / Anzahl der ausgelösten Fail-Save CC-Meldungen

#define I3_PID_KAF__KAFAS_SLI_DATA                                   0x4005
        // _KAFAS_SLI_DATA / _KAFAS_SLI_DATA

    #define I3_RES_KAF_STAT_SLI_AMT_CAM_DET_WERT                     (RXBUF_UINT32(0))
    #define I3_RES_KAF_STAT_SLI_AMT_CAM_DET_WERT_UNIT                'Counts'
    #define I3_RES_KAF_STAT_SLI_AMT_CAM_DET_WERT_TYPE                unsigned long
        // Number of camera detections of traffic signs / Anzahl der Kameradetektionen von Verkehrsschildern

    #define I3_RES_KAF_STAT_SLI_MATCH_URBAN_WERT                     (RXBUF_UCHAR(4))
    #define I3_RES_KAF_STAT_SLI_MATCH_URBAN_WERT_UNIT                'Counts'
    #define I3_RES_KAF_STAT_SLI_MATCH_URBAN_WERT_TYPE                char
        // Share of camera detection that match the explicit speed limits on the street type Urban or Residential Area /
        // Anteil der  Kameradetektion die mit den expliziten Speed Limits auf dem Straßentyp Urban oder Residential Area
        // übereinstimmen

    #define I3_RES_KAF_STAT_SLI_MATCH_RURAL_WERT                     (RXBUF_UCHAR(5))
    #define I3_RES_KAF_STAT_SLI_MATCH_RURAL_WERT_UNIT                'Counts'
    #define I3_RES_KAF_STAT_SLI_MATCH_RURAL_WERT_TYPE                char
        // Proportion of camera detection that corresponds to the explicit speed limits on the road type rural or highway
        // / Anteil der  Kameradetektion die mit den expliziten Speed Limits auf dem Straßentyp Rural oder Highway
        // übereinstimmen

    #define I3_RES_KAF_STAT_SLI_MATCH_MOWAY_WERT                     (RXBUF_UCHAR(6))
    #define I3_RES_KAF_STAT_SLI_MATCH_MOWAY_WERT_UNIT                'Counts'
    #define I3_RES_KAF_STAT_SLI_MATCH_MOWAY_WERT_TYPE                char
        // Percentage of camera detection that corresponds to the explicit speed limits on the road type Motorway /
        // Anteil der  Kameradetektion die mit den expliziten Speed Limits auf dem Straßentyp Motorway übereinstimmen

    #define I3_RES_KAF_STAT_SLI_REP_URBAN_WERT                       (RXBUF_UINT(7))
    #define I3_RES_KAF_STAT_SLI_REP_URBAN_WERT_UNIT                  'm'
    #define I3_RES_KAF_STAT_SLI_REP_URBAN_WERT_TYPE                  unsigned short
        // Average distance at which signs repeat on the street type Urban or Residential Area / Durschnittlich Enfernung
        // in welcher sich Schilder auf dem Straßentyp Urbanoder Residential Area wiederholen

    #define I3_RES_KAF_STAT_SLI_REP_RURAL_WERT                       (RXBUF_UINT(9))
    #define I3_RES_KAF_STAT_SLI_REP_RURAL_WERT_UNIT                  'm'
    #define I3_RES_KAF_STAT_SLI_REP_RURAL_WERT_TYPE                  unsigned short
        // Average distance at which signs repeat on the road type rural or highway / Durschnittlich Enfernung in welcher
        // sich Schilder auf dem Straßentyp Rural oder Highway wiederholen

    #define I3_RES_KAF_STAT_SLI_REP_MOWAY_WERT                       (RXBUF_UINT(11))
    #define I3_RES_KAF_STAT_SLI_REP_MOWAY_WERT_UNIT                  'm'
    #define I3_RES_KAF_STAT_SLI_REP_MOWAY_WERT_TYPE                  unsigned short
        // Average distance at which signs repeat on the road type Motorway / Durschnittlich Enfernung in welcher sich
        // Schilder auf dem Straßentyp Motorway wiederholen

    #define I3_RES_KAF_STAT_SLI_OVER_SLI_WERT                        (RXBUF_UINT32(13))
    #define I3_RES_KAF_STAT_SLI_OVER_SLI_WERT_UNIT                   'km'
    #define I3_RES_KAF_STAT_SLI_OVER_SLI_WERT_TYPE                   unsigned long
        // Distance driven at least 20 km / h above the detected speed limit / Gefahrene Entfernung mit mindestens 20
        // km/h über dem erkannten Speed Limit

    #define I3_RES_KAF_STAT_SLI_SSS_TIME_WERT                        (RXBUF_UINT(17))
    #define I3_RES_KAF_STAT_SLI_SSS_TIME_WERT_UNIT                   'Counts'
    #define I3_RES_KAF_STAT_SLI_SSS_TIME_WERT_TYPE                   unsigned short
        // Number of recognized additional characters with time restriction / Anzahl der erkannten Zusatzzeichen mit
        // Zeitbeschränkung

    #define I3_RES_KAF_STAT_SLI_NPI_WERT                             (RXBUF_UINT32(19))
    #define I3_RES_KAF_STAT_SLI_NPI_WERT_UNIT                        'km'
    #define I3_RES_KAF_STAT_SLI_NPI_WERT_TYPE                        unsigned long
        // Kilometers driven with no overtaking recognized / Gefahrene Kilometer mit erkanntem Überholverbot

    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_DIST_WERT                (RXBUF_UINT(23))
    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_DIST_WERT_UNIT           'Counts'
    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_DIST_WERT_TYPE           unsigned short
        // Number of cancellations of overtaking ban due to exceeding the stopping distance / Anzahl Aufhebungen
        // Überholverbot infolge Überschreitung Haltedistanz

    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_SIGN_WERT                (RXBUF_UINT(25))
    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_SIGN_WERT_UNIT           'Counts'
    #define I3_RES_KAF_STAT_SLI_NP_WITHDRAW_SIGN_WERT_TYPE           unsigned short
        // Number of cancellations No overtaking due to detection of a lifting sign / Anzahl Aufhebungen Überholverbot
        // infolge Detektion Aufhebungsschild

// Skipping _FASTA_FLA_LOESCHEN on 0x4006 which takes arguments

// Skipping _STEURUNG_KALIBRIERDATEN_KAFAS on 0x400A which takes arguments

// Skipping _STEUERN_SLI_NPI_KAMERA_ERKENNUNG on 0x400B which takes arguments

// Skipping _STEURUNG_SHUTDOWN_WATCHDOG on 0x400C which takes arguments

#define I3_PID_KAF__STATUS_SAFETY_DIAG_INFO                          0x400E
        // This job shall respond with information about the errors detected by the Safety Diagnostic Manager. The
        // parameter values shall indicate 0 for fault_not_present and 1 for fault_present. / This job shall respond with
        // information about the errors detected by the Safety Diagnostic Manager. The parameter values shall indicate 0
        // for fault_not_present and 1 for fault_present.

    #define I3_RES_KAF_STAT_BYTE_0_FAULT_WERT                        (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_BYTE_0_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_0_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0
        // UP1V0D_freeze_fault 1 UP1V8D_freeze_fault 2 UP2V5D_freeze_fault 3 UP3V3D_freeze_fault 4 UP5V0D_freeze_fault 5
        // VTEMP1_freeze_fault 6 VTEMP2_freeze_fault 7 V_BAT1_freeze_fault / The parameter values shall indicate 0 for
        // fault_not_present and 1 for fault_present. Bit: 0 UP1V0D_freeze_fault 1 UP1V8D_freeze_fault 2
        // UP2V5D_freeze_fault 3 UP3V3D_freeze_fault 4 UP5V0D_freeze_fault 5 VTEMP1_freeze_fault 6 VTEMP2_freeze_fault 7
        // V_BAT1_freeze_fault

    #define I3_RES_KAF_STAT_BYTE_1_FAULT_WERT                        (RXBUF_UCHAR(1))
    #define I3_RES_KAF_STAT_BYTE_1_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_1_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0
        // UP1V0D_freeze_fault 1 UP1V8D_freeze_fault 2 UP2V5D_freeze_fault 3 UP3V3D_freeze_fault 4 UP5V0D_freeze_fault 5
        // VTEMP1_freeze_fault 6 VTEMP2_freeze_fault 7 V_BAT1_freeze_fault / The parameter values shall indicate 0 for
        // fault_not_present and 1 for fault_present. Bit: 0 UP1V0D_freeze_fault 1 UP1V8D_freeze_fault 2
        // UP2V5D_freeze_fault 3 UP3V3D_freeze_fault 4 UP5V0D_freeze_fault 5 VTEMP1_freeze_fault 6 VTEMP2_freeze_fault 7
        // V_BAT1_freeze_fault

    #define I3_RES_KAF_STAT_BYTE_2_FAULT_WERT                        (RXBUF_UCHAR(2))
    #define I3_RES_KAF_STAT_BYTE_2_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_2_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0
        // UP1V0D_voltage_fault 1 UP1V8D_voltage_fault 2 UP2V5D_voltage_fault 3 UP3V3D_voltage_fault 4
        // UP5V0D_voltage_fault 5 VTEMP1_temperature_fault 6 VTEMP2_temperature_fault 7 V_BAT1_voltage_fault / The
        // parameter values shall indicate 0 for fault_not_present and 1 for fault_present.  Bit: 0 UP1V0D_voltage_fault
        // 1 UP1V8D_voltage_fault 2 UP2V5D_voltage_fault 3 UP3V3D_voltage_fault 4 UP5V0D_voltage_fault 5
        // VTEMP1_temperature_fault 6 VTEMP2_temperature_fault 7 V_BAT1_voltage_fault

    #define I3_RES_KAF_STAT_BYTE_3_FAULT_WERT                        (RXBUF_UCHAR(3))
    #define I3_RES_KAF_STAT_BYTE_3_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_3_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0
        // ECU_inconsistent_temperature_fault / The parameter values shall indicate 0 for fault_not_present and 1 for
        // fault_present. Bit: 0 ECU_inconsistent_temperature_fault

    #define I3_RES_KAF_STAT_BYTE_4_FAULT_WERT                        (RXBUF_UCHAR(4))
    #define I3_RES_KAF_STAT_BYTE_4_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_4_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0 Eq2Unavailable 1
        // Eq2FaultHandlingAliveError 2 Eq2FaultHandlingCrcError 3 VideoError_400 4 TempStatus_400 5 CamLVDS_Defect_400 6
        // CamEEP_Fail_400 7 BurntPixel_400 / The parameter values shall indicate 0 for fault_not_present and 1 for
        // fault_present. Bit: 0 Eq2Unavailable 1 Eq2FaultHandlingAliveError 2 Eq2FaultHandlingCrcError 3 VideoError_400
        // 4 TempStatus_400 5 CamLVDS_Defect_400 6 CamEEP_Fail_400 7 BurntPixel_400

    #define I3_RES_KAF_STAT_BYTE_5_FAULT_WERT                        (RXBUF_UCHAR(5))
    #define I3_RES_KAF_STAT_BYTE_5_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_5_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0 DDR_Failure_400 1
        // WdgMSafetyAliveSupervisonFault / The parameter values shall indicate 0 for fault_not_present and 1 for
        // fault_present. Bit: 0 DDR_Failure_400 1 WdgMSafetyAliveSupervisonFault

    #define I3_RES_KAF_STAT_BYTE_6_FAULT_WERT                        (RXBUF_UCHAR(6))
    #define I3_RES_KAF_STAT_BYTE_6_FAULT_WERT_UNIT                   'HEX'
    #define I3_RES_KAF_STAT_BYTE_6_FAULT_WERT_TYPE                   unsigned char
        // The parameter values shall indicate 0 for fault_not_present and 1 for fault_present. Bit: 0 ActiveFaultClass
        // Bit 0 * 1 ActiveFaultClass Bit 1 * 2 ActiveFaultClass Bit 2 * 3 (not disp_drasy_available) 4 (not
        // aAssistFunctionAvailable) 5 (not qAssistActive) 6 Not in use 7 Safe state entered disp_drasy_available means
        // that the bit is 0 when the signal is available, and 1 when it is not available / The parameter values shall
        // indicate 0 for fault_not_present and 1 for fault_present. Bit: 0 ActiveFaultClass Bit 0* 1 ActiveFaultClass
        // Bit 1* 2 ActiveFaultClass Bit 2* 3 (not disp_drasy_available)  4 (not aAssistFunctionAvailable) 5 (not
        // qAssistActive) 6 Not in use 7 Safe state entered disp_drasy_available  means that the bit is  0  when the
        // signal is availablem, and  1  when it is not available

#define I3_PID_KAF__STATUS_WARNZEITPUNKT_FCW                         0x400F
        // currently selected warning flavor / currently selected warning flavor

    #define I3_RES_KAF_STAT_WARN_FLAV_FCW                            (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_WARN_FLAV_FCW_UNIT                       '0-n'
    #define I3_RES_KAF_STAT_WARN_FLAV_FCW_TYPE                       unsigned char
        // currently selected warning flavor / currently selected warning flavor

#define I3_PID_KAF_FASTA_PPP_DATA                                    0x4010
        // FASTA_PPP_DATA / FASTA_PPP_DATA

    #define I3_RES_KAF_STAT_PPP_WARNING_ZONE                         (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_PPP_WARNING_ZONE_UNIT                    '0-n'
    #define I3_RES_KAF_STAT_PPP_WARNING_ZONE_TYPE                    unsigned short
        // Type of warning zone / Art der Warnzone

    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_0_TO_20_WERT          (RXBUF_UINT(2))
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_0_TO_20_WERT_UNIT     'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_0_TO_20_WERT_TYPE     unsigned short
        // The parameter is determined by counting the number of DZ events in the range 0 <x <20 km / h / Die Kenngröße
        // wird bestimmt, indem die Anzahl der DZ-Events im Bereich 0 < x < 20 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_20_TO_40_WERT         (RXBUF_UINT(4))
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_20_TO_40_WERT_UNIT    'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_20_TO_40_WERT_TYPE    unsigned short
        // The parameter is determined by counting the number of DZ events in the range 20 <x <40 km / h / Die Kenngröße
        // wird bestimmt, indem die Anzahl der DZ-Events im Bereich 20 < x < 40 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_40_TO_60_WERT         (RXBUF_UINT(6))
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_40_TO_60_WERT_UNIT    'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_DZ_EVENTS_40_TO_60_WERT_TYPE    unsigned short
        // The parameter is determined by counting the number of DZ events in the range 40 <x <60 km / h / Die Kenngröße
        // wird bestimmt, indem die Anzahl der DZ-Events im Bereich 40 < x < 60 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_0_TO_20_WERT        (RXBUF_UINT(8))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_0_TO_20_WERT_UNIT   'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_0_TO_20_WERT_TYPE   unsigned short
        // The parameter is determined by counting the number of PDZ1 events in the range 0 <x <20 km / h / Die Kenngröße
        // wird bestimmt, indem die Anzahl der PDZ1-Events im Bereich 0 < x < 20 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_20_TO_40_WERT       (RXBUF_UINT(10))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_20_TO_40_WERT_UNIT  'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_20_TO_40_WERT_TYPE  unsigned short
        // The parameter is determined by counting the number of PDZ1 events in the range 20 <x <40 km / h / Die
        // Kenngröße wird bestimmt, indem die Anzahl der PDZ1-Events im Bereich 20 < x < 40 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_40_TO_60_WERT       (RXBUF_UINT(12))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_40_TO_60_WERT_UNIT  'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ1_EVENTS_40_TO_60_WERT_TYPE  unsigned short
        // The parameter is determined by counting the number of PDZ1 events in the range 40 <x <60 km / h / Die
        // Kenngröße wird bestimmt, indem die Anzahl der PDZ1-Events im Bereich 40 < x < 60 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_0_TO_20_WERT        (RXBUF_UINT(14))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_0_TO_20_WERT_UNIT   'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_0_TO_20_WERT_TYPE   unsigned short
        // The parameter is determined by counting the number of PDZ2 events in the range 0 <x <20 km / h / Die Kenngröße
        // wird bestimmt, indem die Anzahl der PDZ2-Events im Bereich 0 < x < 20 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_20_TO_40_WERT       (RXBUF_UINT(16))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_20_TO_40_WERT_UNIT  'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_20_TO_40_WERT_TYPE  unsigned short
        // The parameter is determined by counting the number of PDZ2 events in the range 20 <x <40 km / h / Die
        // Kenngröße wird bestimmt, indem die Anzahl der PDZ2-Events im Bereich 20 < x < 40 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_40_TO_60_WERT       (RXBUF_UINT(18))
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_40_TO_60_WERT_UNIT  'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PDZ2_EVENTS_40_TO_60_WERT_TYPE  unsigned short
        // The parameter is determined by counting the number of PDZ2 events in the range 40 <x <60 km / h / Die
        // Kenngröße wird bestimmt, indem die Anzahl der PDZ2-Events im Bereich 40 < x < 60 km/h gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_PREWARNUNG_REQUESTS_WERT        (RXBUF_UINT(20))
    #define I3_RES_KAF_STAT_PPP_AMNT_PREWARNUNG_REQUESTS_WERT_UNIT   'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PREWARNUNG_REQUESTS_WERT_TYPE   unsigned short
        // The parameter is determined by counting the number of pre-warning requests / Die Kenngröße wird bestimmt,
        // indem die Anzahl der Pre-Warning-Requests gezählt wird

    #define I3_RES_KAF_STAT_PPP_AMNT_ACUTEWARNING_REQUESTS_WERT      (RXBUF_UINT(22))
    #define I3_RES_KAF_STAT_PPP_AMNT_ACUTEWARNING_REQUESTS_WERT_UNIT 'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_ACUTEWARNING_REQUESTS_WERT_TYPE unsigned short
        // The parameter is determined by counting the number of acute warning requests. / Die Kenngröße wird bestimmt,
        // indem die Anzahl der Acute-Warning-Requests gezählt wird.

    #define I3_RES_KAF_STAT_PPP_AMNT_HBA_REQUESTS_WERT               (RXBUF_UINT(24))
    #define I3_RES_KAF_STAT_PPP_AMNT_HBA_REQUESTS_WERT_UNIT          'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_HBA_REQUESTS_WERT_TYPE          unsigned short
        // The parameter is determined by counting the number of HBA requests. / Die Kenngröße wird bestimmt, indem die
        // Anzahl der HBA-Requests gezählt wird.

    #define I3_RES_KAF_STAT_PPP_AMNT_PREFILL_REQUESTS_WERT           (RXBUF_UINT(26))
    #define I3_RES_KAF_STAT_PPP_AMNT_PREFILL_REQUESTS_WERT_UNIT      'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_PREFILL_REQUESTS_WERT_TYPE      unsigned short
        // The parameter is determined by counting the number of prefill requests. / Die Kenngröße wird bestimmt, indem
        // die Anzahl der Prefill-Requests gezählt wird.

    #define I3_RES_KAF_STAT_PPP_AMNT_BRAKE_REQUESTS_WERT             (RXBUF_UINT(28))
    #define I3_RES_KAF_STAT_PPP_AMNT_BRAKE_REQUESTS_WERT_UNIT        'Counts'
    #define I3_RES_KAF_STAT_PPP_AMNT_BRAKE_REQUESTS_WERT_TYPE        unsigned short
        // The parameter is determined by counting the number of brake requests. / Die Kenngröße wird bestimmt, indem die
        // Anzahl der Brake-Requests gezählt wird.

    #define I3_RES_KAF_STAT_PPP_DEACT_DRIVER_WERT                    (RXBUF_UINT(30))
    #define I3_RES_KAF_STAT_PPP_DEACT_DRIVER_WERT_UNIT               'Counts'
    #define I3_RES_KAF_STAT_PPP_DEACT_DRIVER_WERT_TYPE               unsigned short
        // The parameter is determined by counting the number of times the pFGS function was switched off by the driver.
        // (Status change of the activation by pressing the button) / Die Kenngröße wird bestimmt, indem die Anzahl der
        // Abschaltungen der Funktion pFGS durch den Fahrer gezählt wird. (Statuswechsel der Aktivierung durch
        // Tasterbetätigung)

    #define I3_RES_KAF_STAT_PPP_DEACT_AVAILABILITY_WERT              (RXBUF_UINT(32))
    #define I3_RES_KAF_STAT_PPP_DEACT_AVAILABILITY_WERT_UNIT         'Counts'
    #define I3_RES_KAF_STAT_PPP_DEACT_AVAILABILITY_WERT_TYPE         unsigned short
        // The parameter is determined by counting the number of times the pFGS function was switched off by the KAFAS
        // system based on the availability concept (e.g. recognition qualifier, degradation concept, ...). / Die
        // Kenngröße wird bestimmt, indem die Anzahl der Abschaltungen der Funktion pFGS durch das KAFAS System aufgrund
        // des Verfügbarkeitskonzeptes (z.B. Erkennungsqualifier, Degradationskonzept,...) gezählt wird.

    #define I3_RES_KAF_STAT_PPP_DEACT_WARNING_CHAIN_WERT             (RXBUF_UINT(34))
    #define I3_RES_KAF_STAT_PPP_DEACT_WARNING_CHAIN_WERT_UNIT        'Counts'
    #define I3_RES_KAF_STAT_PPP_DEACT_WARNING_CHAIN_WERT_TYPE        unsigned short
        // The parameter is determined by counting the number of times the pPP function has been switched off by the
        // KAFAS system based on the braking and warning chain. / Die Kenngröße wird bestimmt, indem die Anzahl der
        // Abschaltungen der Funktion pPP durch das KAFAS System aufgrund der Brems-und Warnkette gezählt wird.

    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_CL50_WERT             (RXBUF_UINT32(36))
    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_CL50_WERT_UNIT        's'
    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_CL50_WERT_TYPE        unsigned long
        // The parameter is determined by always counting the operating time in seconds from terminal 50. / Die Kenngröße
        // wird bestimmt, indem immer ab Kl 50 die Betriebszeit in Sekunden gezählt wird.

    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_ACTIVE_WERT           (RXBUF_UINT32(40))
    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_ACTIVE_WERT_UNIT      's'
    #define I3_RES_KAF_STAT_PPP_OPERATION_TIME_ACTIVE_WERT_TYPE      unsigned long
        // The parameter is determined by always counting the operating time in seconds from terminal 50 while the pFGS
        // function is activated. / Die Kenngröße wird bestimmt, indem immer ab Kl 50 die Betriebszeit in Sekunden
        // gezählt wird, während die pFGS-Funktion aktiviert ist.

    #define I3_RES_KAF_STAT_PPP_FS_CC_WERT                           (RXBUF_UINT(44))
    #define I3_RES_KAF_STAT_PPP_FS_CC_WERT_UNIT                      'Counts'
    #define I3_RES_KAF_STAT_PPP_FS_CC_WERT_TYPE                      unsigned short
        // The parameter is determined by counting the number of Check Control messages triggered due to reduced
        // visibility for the pFGS function. / Die Kenngröße wird bestimmt, indem die Anzahl der ausgelösten Check
        // Control Meldungen aufgrund reduzierter Sicht für die Funktion pFGS gezählt wird.

    #define I3_RES_KAF_STAT_PPP_DRIVEN_TIME_FS_ACT_WERT              (RXBUF_UINT32(46))
    #define I3_RES_KAF_STAT_PPP_DRIVEN_TIME_FS_ACT_WERT_UNIT         's'
    #define I3_RES_KAF_STAT_PPP_DRIVEN_TIME_FS_ACT_WERT_TYPE         unsigned long
        // The parameter is determined by determining the operating time from Kl 50 in seconds in which pFGS is in the
        // reduced visibility status and activated by the driver. / Die Kenngröße wird bestimmt, indem die Betriebszeit
        // ab Kl 50 in Sekunden ermittelt wird, in der pFGS im Status  reduzierte Sicht  und vom Fahrer aktiviert ist.

#define I3_PID_KAF_FASTA_CCM_DATA                                    0x4011
        // FASTA_CCM_DATA / FASTA_CCM_DATA

    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_20_WERT                   (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_20_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_20_WERT_TYPE              unsigned short
        // The parameter is determined by counting the number of CCM brakes in which the speed of the host vehicle at the
        // start of braking is greater than or equal to 0 km / h and less than 20 km / h. / Die Kenngröße wird bestimmt,
        // indem die Anzahl der CCM-Bremsungen gezählt wird, bei denen die Geschwindigkeit des Egofahrzeugs zu
        // Bremsbeginn größer gleich 0 km/h und kleiner 20 km/h ist.

    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_40_WERT                   (RXBUF_UINT(2))
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_40_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_40_WERT_TYPE              unsigned short
        // The parameter is determined by counting the number of CCM brakes in which the speed of the host vehicle at the
        // start of braking is greater than or equal to 20 km / h and less than 40 km / h. / Die Kenngröße wird bestimmt,
        // indem die Anzahl der CCM-Bremsungen gezählt wird, bei denen die Geschwindigkeit des Egofahrzeugs zu
        // Bremsbeginn größer gleich 20 km/h und kleiner 40 km/h ist.

    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_GEQ40_WERT                (RXBUF_UINT(4))
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_GEQ40_WERT_UNIT           'Counts'
    #define I3_RES_KAF_STAT_CCM_AMNT_BRAKE_GEQ40_WERT_TYPE           unsigned short
        // The parameter is determined by counting the number of CCM brakes in which the speed of the host vehicle is
        // greater than or equal to 40 km / h at the beginning of the braking / Die Kenngröße wird bestimmt, indem die
        // Anzahl der CCM-Bremsungen gezählt wird, bei denen die Geschwindigkeit des Egofahrzeugs zu Bremsbeginn größer
        // gleich 40 km/h ist

#define I3_PID_KAF__KAFAS_ENVINT_DATA                                0x4012
        // _KAFAS_ENVINT_DATA / _KAFAS_ENVINT_DATA

    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_DIST_FS_WERT               (RXBUF_UINT32(0))
    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_DIST_FS_WERT_UNIT          'km'
    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_DIST_FS_WERT_TYPE          unsigned long
        // Cont the number of km driven with degraded availability / Cont the number of km driven with degraded
        // availability

    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_TIME_FS_WERT               (RXBUF_UINT32(4))
    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_TIME_FS_WERT_UNIT          's'
    #define I3_RES_KAF_STAT_ENVINT_DRIVEN_TIME_FS_WERT_TYPE          unsigned long
        // Count the time in seconds driven with degraded availability / Count the time in seconds driven with degraded
        // availability

// Skipping _STEUERN_WARNAUSGABE_PPP on 0x4015 which takes arguments

#define I3_PID_KAF_PPP_ANFORDERUNGEN                                 0x4016
        // This job shall respond with the timestamp and type of warning. It shall be possible to read the information
        // over a clamp change, which means the information needs to be store in a NVRAM. The response value shall be set
        // to 0x00 as default value (i.e. if no acute warning or brake request have been triggered this job shall respond
        // with zeros) The type of warning and timestamps shall be related to the type of warning. 1) Acute warning
        // request When signal WARN_HDWOBS_FGS in message 198h (SYS3637) is set to 0001b Timestamp_acute = the actual
        // system time when the warning happened. 2) Brake request When signal TAR_DCRN_FGS in the message 198h (SYS3637)
        // changes from 0xFE to a value less than 0xFE. Timestamp_brake = the actual system time when the warning
        // happened. / This job shall respond with the timestamp and type of warning.  It shall be possible to read the
        // information over a clamp change, which means the information needs to be store in a NVRAM.  The response value
        // shall be set to 0x00 as default value (i.e. if no acute warning or brake request have been triggered this job
        // shall respond with zeros)  The type of warning and timestamps shall be related to the type of warning. 1)
        // Acute warning request  When signal WARN_HDWOBS_FGS in message 198h (SYS3637) is set to 0001b Timestamp_acute =
        // the actual system time when the warning happened.  2) Brake request When signal TAR_DCRN_FGS in the message
        // 198h (SYS3637) changes from 0xFE to a value less than 0xFE. Timestamp_brake = the actual system time when the
        // warning happened.

    #define I3_RES_KAF_STAT_TYPE_OF_WARNING                          (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_TYPE_OF_WARNING_UNIT                     '0-n'
    #define I3_RES_KAF_STAT_TYPE_OF_WARNING_TYPE                     unsigned char
        // 0x01 if only a Brake request according to 2) is triggered 0x02 if only an Acute warning request according to
        // 1) is triggered 0x03 if both an Acute warning request and a Brake request is triggered / 0x01 if only a Brake
        // request according to 2) is triggered 0x02 if only an Acute warning request according to 1)  is triggered 0x03
        // if both an Acute warning request and a Brake request is triggered

    #define I3_RES_KAF_STAT_TIMESTAMP_ACUTE_WERT                     (RXBUF_UINT32(1))
    #define I3_RES_KAF_STAT_TIMESTAMP_ACUTE_WERT_UNIT                's'
    #define I3_RES_KAF_STAT_TIMESTAMP_ACUTE_WERT_TYPE                unsigned long
        // The time stamp is the system time value (message 328h) when the warning happened / The time stamp is the
        // system time value (message 328h) when the warning happened

    #define I3_RES_KAF_STAT_TIMESTAMP_BRAKE_WERT                     (RXBUF_UINT32(5))
    #define I3_RES_KAF_STAT_TIMESTAMP_BRAKE_WERT_UNIT                's'
    #define I3_RES_KAF_STAT_TIMESTAMP_BRAKE_WERT_TYPE                unsigned long
        // The time stamp is the system time value (message 328h) when the warning happened. / The time stamp is the
        // system time value (message 328h) when the warning happened.

#define I3_PID_KAF__GENERIC_EYEQ2_INFO                               0x4017
        // EyeQ2 restarts, 1 byte Counter for number of EyeQ2 restarts caused by camera error debouncing as described in
        // DTC 0x800ABB - Camera Connection Error / EyeQ2 restarts, 1 byte Counter for number of EyeQ2 restarts caused by
        // camera error  debouncing  as described in DTC 0x800ABB - Camera Connection Error

    #define I3_RES_KAF_STAT_EYEQ2_RESTARTS_WERT                      (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_EYEQ2_RESTARTS_WERT_UNIT                 'Counts'
    #define I3_RES_KAF_STAT_EYEQ2_RESTARTS_WERT_TYPE                 unsigned char
        // EyeQ2 restarts, 1 byte Counter for number of EyeQ2 restarts caused by camera error debouncing as described in
        // DTC 0x800ABB - Camera Connection Error / EyeQ2 restarts, 1 byte Counter for number of EyeQ2 restarts caused by
        // camera error  debouncing  as described in DTC 0x800ABB - Camera Connection Error

// Skipping _RESET_GENERIC_EYEQ2_INFO on 0x4018 which takes arguments

#define I3_PID_KAF__STATUS_CAMERA_MONITORING_WERT                    0x4050
        // The DID can be used to monitor the status of the camera -> EyeQ2 image transfer, as well as the camera
        // temperature. / The DID can be used to monitor the status of the camera -> EyeQ2 image transfer, as well as the
        // camera temperature.

    #define I3_RES_KAF_STAT_FRAME_INDEX_WERT                         (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_FRAME_INDEX_WERT_UNIT                    'Counts'
    #define I3_RES_KAF_STAT_FRAME_INDEX_WERT_TYPE                    unsigned short
        // This is a frame counter, that shall be increased for every frame that is not skipped. Frames that are skipped
        // for any reason shall not increment this counter. When the counter reaches over 65535, it shall restart from 0.
        // The counter shall restart from 0 at every startup of the EyeQ2. / This is a frame counter, that shall be
        // increased for every frame that is not skipped. Frames that are skipped for any reason shall not increment this
        // counter. When the counter reaches over 65535, it shall restart from 0. The counter shall restart from 0 at
        // every startup of the EyeQ2.

    #define I3_RES_KAF_STAT_VIDEO_ERROR_COUNT_WERT                   (RXBUF_UINT(2))
    #define I3_RES_KAF_STAT_VIDEO_ERROR_COUNT_WERT_UNIT              'Counts'
    #define I3_RES_KAF_STAT_VIDEO_ERROR_COUNT_WERT_TYPE              unsigned short
        // The number of bad frames received from the camera (frames dropped due to data / sync errors). This counter
        // shall be increased with one for each cycle the video error signal is set in the 0x400 message. / The number of
        // bad frames received from the camera (frames dropped due to data/sync errors). This counter shall be increased
        // with one for each cycle the  Video error  signal is set in the 0x400 message.

    #define I3_RES_KAF_STAT_DROPPED_FRAME_COUNT_WERT                 (RXBUF_UINT(4))
    #define I3_RES_KAF_STAT_DROPPED_FRAME_COUNT_WERT_UNIT            'Counts'
    #define I3_RES_KAF_STAT_DROPPED_FRAME_COUNT_WERT_TYPE            unsigned short
        // The number of dropped frames. This counter shall be increased when there is a video error and when the EyeQ2
        // skips a frame for any other reason, such as too long processing time for the preceding frame. / The number of
        // dropped frames. This counter shall be increased when there is a video error and when the EyeQ2 skips a frame
        // for any other reason, such as too long processing time for the preceding frame.

    #define I3_RES_KAF_STAT_CAMERA_TEMP_WERT                         (RXBUF_UCHAR(6)-60.0)
    #define I3_RES_KAF_STAT_CAMERA_TEMP_WERT_UNIT                    '°C'
    #define I3_RES_KAF_STAT_CAMERA_TEMP_WERT_TYPE                    unsigned char
        // The camera temperature, as read by the EyeQ2 via I2C. The camera temperature shall be read from the EyeQ2
        // every 10 seconds. / The camera temperature, as read by the EyeQ2 via I2C. The camera temperature shall be read
        // from the EyeQ2 every 10 seconds.

// Skipping STEUERN_ANZEIGE_KOMBI_TLC on 0xA37C which takes arguments

#define I3_PID_KAF_ABSCHALTGRUND_FERNLICHT                           0xD341
        // Reasons for switching off high beam. / Abschaltgründe für Fernlicht.

    #define I3_RES_KAF_STAT_FLA_ENTGEGENKOMMENDES_FAHRZEUG           (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_FLA_ENTGEGENKOMMENDES_FAHRZEUG_UNIT      '0/1'
    #define I3_RES_KAF_STAT_FLA_ENTGEGENKOMMENDES_FAHRZEUG_TYPE      unsigned char
        // Indicates whether an oncoming vehicle has been detected: 0 = no vehicle detected, 1 = vehicle detected / Gibt
        // aus, ob ein entgegenkommendes Fahrzeug erkannt worden ist:  0 = kein Fahrzeug erkannt,  1 = Fahrzeug erkannt

    #define I3_RES_KAF_STAT_FLA_VORAUSFAHRENDES_FAHRZEUG             (RXBUF_UCHAR(1))
    #define I3_RES_KAF_STAT_FLA_VORAUSFAHRENDES_FAHRZEUG_UNIT        '0/1'
    #define I3_RES_KAF_STAT_FLA_VORAUSFAHRENDES_FAHRZEUG_TYPE        unsigned char
        // Indicates whether a vehicle in front has been detected: 0 = no vehicle detected, 1 = vehicle detected / Gibt
        // aus, ob ein vorausfahrendes Fahrzeug erkannt worden ist:  0 = kein Fahrzeug erkannt,  1 = Fahrzeug erkannt

    #define I3_RES_KAF_STAT_FLA_GESCHWINDIGKEITSLIMIT                (RXBUF_UCHAR(2))
    #define I3_RES_KAF_STAT_FLA_GESCHWINDIGKEITSLIMIT_UNIT           '0/1'
    #define I3_RES_KAF_STAT_FLA_GESCHWINDIGKEITSLIMIT_TYPE           unsigned char
        // Indicates whether the speed below the limit has been detected: 0 = speed above the threshold, high beam is
        // switched on, 1 = speed below the threshold, high beam is switched off / Gibt aus, ob die Geschwindigkeit
        // unterhalb der Grenze erkannt worden ist:  0 = Geschwindigkeit oberhalb der Schwelle, Fernlicht wird
        // eingeschaltet,  1 = Geschwindigkeit unterhalb der Schwelle, Fernlicht wird abgeschaltet

    #define I3_RES_KAF_STAT_FLA_UMGEBUNGSHELLIGKEIT                  (RXBUF_UCHAR(3))
    #define I3_RES_KAF_STAT_FLA_UMGEBUNGSHELLIGKEIT_UNIT             '0/1'
    #define I3_RES_KAF_STAT_FLA_UMGEBUNGSHELLIGKEIT_TYPE             unsigned char
        // Indicates whether ambient brightness (day) has been recognized: 0 = no brightness (night) recognized, 1 =
        // brightness (day) recognized / Gibt aus, ob Umgebungshelligkeit (Tag) erkannt worden ist:  0 = kein Helligkeit
        // (Nacht) erkannt,  1 = Helligkeit (Tag) erkannt

    #define I3_RES_KAF_STAT_FLA_ORTSCHAFTSERKENNUNG                  (RXBUF_UCHAR(4))
    #define I3_RES_KAF_STAT_FLA_ORTSCHAFTSERKENNUNG_UNIT             '0/1'
    #define I3_RES_KAF_STAT_FLA_ORTSCHAFTSERKENNUNG_TYPE             unsigned char
        // Indicates whether sufficient lighting has been detected: 0 = insufficient lighting detected, 1 = sufficient
        // lighting detected / Gibt aus, ob eine ausreichende Beleuchtung erkannt worden ist:  0 = keine ausreichende
        // Beleuchtung erkannt,  1 = ausreichende Beleuchtung erkannt

    #define I3_RES_KAF_STAT_FLA_NEBELERKENNUNG                       (RXBUF_UCHAR(5))
    #define I3_RES_KAF_STAT_FLA_NEBELERKENNUNG_UNIT                  '0/1'
    #define I3_RES_KAF_STAT_FLA_NEBELERKENNUNG_TYPE                  unsigned char
        // Indicates whether fog has been detected: 0 = no fog, 1 = fog detected / Gibt aus, ob Nebel erkannt worden ist:
        // 0 = kein Nebel,  1 = Nebel erkannt

    #define I3_RES_KAF_STAT_FLA_AUTOBAHNMODE                         (RXBUF_UCHAR(6))
    #define I3_RES_KAF_STAT_FLA_AUTOBAHNMODE_UNIT                    '0/1'
    #define I3_RES_KAF_STAT_FLA_AUTOBAHNMODE_TYPE                    unsigned char
        // Indicates whether a motorway has been recognized: 0 = no motorway, 1 = motorway recognized / Gibt aus, ob
        // Autobahn erkannt worden ist:  0 = keine Autobahn,  1 = Autobahn erkannt

    #define I3_RES_KAF_STAT_FLA_VERZOEGERUNGSZEIT                    (RXBUF_UCHAR(7))
    #define I3_RES_KAF_STAT_FLA_VERZOEGERUNGSZEIT_UNIT               '0/1'
    #define I3_RES_KAF_STAT_FLA_VERZOEGERUNGSZEIT_TYPE               unsigned char
        // Indicates whether the high beam is not switched on due to a time delay: 0 = no time delay, 1 = time delay /
        // Gibt aus, ob wegen einer Zeiterzögerung das Fernlicht nicht eingeschaltet wird:  0 = keine Zeitverzögerung,  1
        // = Zeitverzögerung

#define I3_PID_KAF_KONFIGURATION_KAFAS                               0xD374
        // Issue of equipment from KAFAS / Ausgabe der Ausstattung von KAFAS

    #define I3_RES_KAF_STAT_VORHANDEN_TLC                            (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_VORHANDEN_TLC_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_TLC_TYPE                       unsigned char
        // Indicates whether the time-to-line crossing function is available: 0 = not available; 1 = present / Gibt an,
        // ob die Funktion Time-to-Line Crossing vorhanden ist: 0= nicht vorhanden; 1= vorhanden

    #define I3_RES_KAF_STAT_VORHANDEN_FLA                            (RXBUF_UCHAR(1))
    #define I3_RES_KAF_STAT_VORHANDEN_FLA_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_FLA_TYPE                       unsigned char
        // Indicates whether the high beam assistant function is available: 0 = not available; 1 = present / Gibt an, ob
        // die Funktion Fernlichtassistent vorhanden ist: 0= nicht vorhanden; 1= vorhanden

    #define I3_RES_KAF_STAT_VORHANDEN_SLI                            (RXBUF_UCHAR(2))
    #define I3_RES_KAF_STAT_VORHANDEN_SLI_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_SLI_TYPE                       unsigned char
        // Indicates whether the Speed-Limit-Info function is available: 0 = not available; 1 = present / Gibt an, ob die
        // Funktion Speed-Limit-Info vorhanden ist: 0= nicht vorhanden; 1= vorhanden

    #define I3_RES_KAF_STAT_VORHANDEN_NPI                            (RXBUF_UCHAR(3))
    #define I3_RES_KAF_STAT_VORHANDEN_NPI_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_NPI_TYPE                       unsigned char
        // Indicates whether the NoPassing-Info function is available: 0 = not available; 1 = present / Gibt an, ob die
        // Funktion NoPassing-Info vorhanden ist: 0= nicht vorhanden; 1= vorhanden

    #define I3_RES_KAF_STAT_VORHANDEN_FCW                            (RXBUF_UCHAR(4))
    #define I3_RES_KAF_STAT_VORHANDEN_FCW_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_FCW_TYPE                       unsigned char
        // Indicates whether the Forward Collision Warning function is available: 0 = not available; 1 = present / Gibt
        // an, ob die Funktion Forward-Collision-Warning vorhanden ist: 0= nicht vorhanden; 1= vorhanden

    #define I3_RES_KAF_STAT_VORHANDEN_PED                            (RXBUF_UCHAR(5))
    #define I3_RES_KAF_STAT_VORHANDEN_PED_UNIT                       '0/1'
    #define I3_RES_KAF_STAT_VORHANDEN_PED_TYPE                       unsigned char
        // Indicates whether the Pedistrian Recognition function is available: 0 = not available; 1 = present / Gibt an,
        // ob die Funktion Pedistrian Recognition (Fußgängererkennung) vorhanden ist: 0= nicht vorhanden; 1= vorhanden

#define I3_PID_KAF_KAFAS_VINS_LESEN                                  0xD393
        // Reading out the chassis number from the camera and the control unit. / Auslesen der Fahrgestellnummer aus der
        // Kamera und dem Steuergerät.

    // Can't yet generate code for STAT_KAFAS_KAM_VIN_TEXT of type string[7], at offset 0. But we account for the 7 bytes
        // Output of the 7-digit chassis number from the camera. / Ausgabe der 7-stelligen Fahrgestellnummer aus der
        // Kamera.

    // Can't yet generate code for STAT_KAFAS_ECU_VIN_TEXT of type string[7], at offset 7. But we account for the 7 bytes
        // Output of the 7-digit chassis number from the control unit. / Ausgabe der 7-stelligen Fahrgestellnummer aus
        // dem Steuergerät.

    #define I3_RES_KAF_STAT_KAFAS_VIN_STATUS_NR                      (RXBUF_UCHAR(14))
    #define I3_RES_KAF_STAT_KAFAS_VIN_STATUS_NR_UNIT                 '0-n'
    #define I3_RES_KAF_STAT_KAFAS_VIN_STATUS_NR_TYPE                 unsigned char
        // Indicates whether the assignment of camera to control unit matches: 0x00: NO MATCH, 0x01: MATCH / Gibt aus, ob
        // die Zuordnung Kamera zu Steuergerät übereinstimmt:  0x00: KEINE UEBEREINSTIMMUNG,  0x01: UEBEREINSTIMMUNG

#define I3_PID_KAF_KALIBRIERDATEN_KAFAS                              0xD396
        // Output of the calibration data from the KAFAS camera / Ausgabe der Kalibrierdaten der KAFAS-Kamera

    #define I3_RES_KAF_STAT_OFFLINE_YAW_WERT                         (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_OFFLINE_YAW_WERT_UNIT                    'Pixel'
    #define I3_RES_KAF_STAT_OFFLINE_YAW_WERT_TYPE                    unsigned short
        // Offline yaw angle / Offline Yaw-Winkel

    #define I3_RES_KAF_STAT_OFFLINE_HORIZON_WERT                     (RXBUF_UINT(2))
    #define I3_RES_KAF_STAT_OFFLINE_HORIZON_WERT_UNIT                'Pixel'
    #define I3_RES_KAF_STAT_OFFLINE_HORIZON_WERT_TYPE                unsigned short
        // Offline horizon angle / Offline Horizon-Winkel

    #define I3_RES_KAF_STAT_OFFLINE_ROLL_WERT                        (RXBUF_UINT(4)/100.0f)
    #define I3_RES_KAF_STAT_OFFLINE_ROLL_WERT_UNIT                   'Grad'
    #define I3_RES_KAF_STAT_OFFLINE_ROLL_WERT_TYPE                   float
        // Offline roll angle / Offline Roll-Winkel

    #define I3_RES_KAF_STAT_ONLINE_YAW_WERT                          (RXBUF_UINT(6))
    #define I3_RES_KAF_STAT_ONLINE_YAW_WERT_UNIT                     'Pixel'
    #define I3_RES_KAF_STAT_ONLINE_YAW_WERT_TYPE                     unsigned short
        // Online yaw angle / Online Yaw-Winkel

    #define I3_RES_KAF_STAT_ONLINE_HORIZON_WERT                      (RXBUF_UINT(8))
    #define I3_RES_KAF_STAT_ONLINE_HORIZON_WERT_UNIT                 'Pixel'
    #define I3_RES_KAF_STAT_ONLINE_HORIZON_WERT_TYPE                 unsigned short
        // Online horizon angle / Online Horizon-Winkel

    #define I3_RES_KAF_STAT_ONLINE_ROLL_WERT                         (RXBUF_UINT(10)/100.0f)
    #define I3_RES_KAF_STAT_ONLINE_ROLL_WERT_UNIT                    'Grad'
    #define I3_RES_KAF_STAT_ONLINE_ROLL_WERT_TYPE                    float
        // Online roll angle / Online Roll-Winkel

    #define I3_RES_KAF_STAT_KAM_HOEHE_WERT                           (RXBUF_UINT(12))
    #define I3_RES_KAF_STAT_KAM_HOEHE_WERT_UNIT                      'mm'
    #define I3_RES_KAF_STAT_KAM_HOEHE_WERT_TYPE                      unsigned short
        // Camera installation height / Kamera-Verbauhöhe

    #define I3_RES_KAF_STAT_BRENNWEITE_WERT                          (RXBUF_UINT(14))
    #define I3_RES_KAF_STAT_BRENNWEITE_WERT_UNIT                     'Pixel'
    #define I3_RES_KAF_STAT_BRENNWEITE_WERT_TYPE                     unsigned short
        // Focal length / Brennweite

    #define I3_RES_KAF_STAT_GRABBING_SHIFT_WERT                      (RXBUF_UINT(16))
    #define I3_RES_KAF_STAT_GRABBING_SHIFT_WERT_UNIT                 'Pixel'
    #define I3_RES_KAF_STAT_GRABBING_SHIFT_WERT_TYPE                 unsigned short
        // Grabbing shift / Grabbing-Shift

    // Can't yet generate code for STAT_FAHRGESTELLNR_TEXT of type string[7], at offset 18. But we account for the 7 bytes
        // Chassis number in the camera / Fahrgestellnummer in der Kamera

#define I3_PID_KAF_KAMERAVERBINDUNG_ECU                              0xD397
        // For values see TAB_KAM_VERBINDUNG / Werte siehe TAB_KAM_VERBINDUNG

    #define I3_RES_KAF_STAT_KAFAS_VERBINDUNG_KAM_NR                  (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_KAFAS_VERBINDUNG_KAM_NR_UNIT             '0-n'
    #define I3_RES_KAF_STAT_KAFAS_VERBINDUNG_KAM_NR_TYPE             unsigned char
        // For values see TAB_KAM_VERBINDUNG / Werte siehe TAB_KAM_VERBINDUNG

// Skipping TLC_AKTUATOR on 0xD399 which takes arguments

// Skipping DEMO_MODE_FLA on 0xD3A6 which takes arguments

// Skipping FCW_WARNAUSGABE on 0xD3A7 which takes arguments

// Skipping FCW_VERFUEGBARKEITSVERLUST on 0xD3A8 which takes arguments

// Skipping STEUERN_ANZEIGE_KOMBI_SLI on 0xD3A9 which takes arguments

#define I3_PID_KAF_ERGEBNIS_SLI                                      0xD3AA
        // Output of the result of the traffic sign recognition. / Ausgabe des Ergebnis der Verkehrzeichenerkennung.

    #define I3_RES_KAF_STAT_KAMERA_ZEICHEN_NR                        (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_KAMERA_ZEICHEN_NR_UNIT                   '0-n'
    #define I3_RES_KAF_STAT_KAMERA_ZEICHEN_NR_TYPE                   unsigned char
        // Indicates which character was recognized by the camera: Results see TAB_ZEICHEN_KAMERA / Gibt aus, welches
        // Zeichen von der Kamera erkannt wurde:  Results siehe TAB_ZEICHEN_KAMERA

    #define I3_RES_KAF_STAT_KAMERA_GESCHWINDIGKEIT_WERT              (RXBUF_UCHAR(1))
    #define I3_RES_KAF_STAT_KAMERA_GESCHWINDIGKEIT_WERT_TYPE         unsigned char
        // Indicates the speed that was recognized in the characters: 0 = cancellation of everything, 5 to 150 in steps
        // of 5. / Gibt aus, welche Geschwindigkeit in den Zeichen erkannt wurde: 0 = Aufhebung alles, 5 bis 150 in 5-er
        // Schritten.

    #define I3_RES_KAF_STAT_KARTE_ZEICHEN_NR                         (RXBUF_UCHAR(2))
    #define I3_RES_KAF_STAT_KARTE_ZEICHEN_NR_UNIT                    '0-n'
    #define I3_RES_KAF_STAT_KARTE_ZEICHEN_NR_TYPE                    unsigned char
        // Indicates which character was read from the card: For results see TAB_ZEICHEN_KARTE / Gibt aus, welches
        // Zeichen aus der Karte gelesen wurde:  Results siehe TAB_ZEICHEN_KARTE

    #define I3_RES_KAF_STAT_KARTE_GESCHWINDIGKEIT_WERT               (RXBUF_UCHAR(3))
    #define I3_RES_KAF_STAT_KARTE_GESCHWINDIGKEIT_WERT_TYPE          unsigned char
        // Indicates the speed that was read from the card: 0 = cancel everything, 5 to 150 in steps of 5. / Gibt aus,
        // welche Geschwindigkeit aus der Karte gelesen wurde: 0 = Aufhebung alles, 5 bis 150 in 5-er Schritten.

    #define I3_RES_KAF_STAT_FUSIONIERT_ZEICHEN_NR                    (RXBUF_UCHAR(4))
    #define I3_RES_KAF_STAT_FUSIONIERT_ZEICHEN_NR_UNIT               '0-n'
    #define I3_RES_KAF_STAT_FUSIONIERT_ZEICHEN_NR_TYPE               unsigned char
        // Indicates which character is output from the merged recognition result: Results see TAB_ZEICHEN_FUSIONIERT /
        // Gibt aus, welches Zeichen aus den fusioniertem Erkennungsergebnis ausgegeben wird: Results siehe
        // TAB_ZEICHEN_FUSIONIERT

    #define I3_RES_KAF_STAT_FUSIONIERT_GESCHWINDIGKEIT_WERT          (RXBUF_UCHAR(5))
    #define I3_RES_KAF_STAT_FUSIONIERT_GESCHWINDIGKEIT_WERT_TYPE     unsigned char
        // Outputs the speed from the merged recognition result: 0 = cancel everything, 5 to 150 in steps of 5 / Gibt
        // aus, welche Geschwindigkeit aus dem fusionierten Erkennungsergebnis ausgegeben wird: 0 = Aufhebung alles, 5
        // bis 150 in 5-er Schritten

    #define I3_RES_KAF_STAT_GUETE_KAM_SLI_GESCHW_WERT                (RXBUF_UCHAR(6))
    #define I3_RES_KAF_STAT_GUETE_KAM_SLI_GESCHW_WERT_UNIT           '%'
    #define I3_RES_KAF_STAT_GUETE_KAM_SLI_GESCHW_WERT_TYPE           unsigned char
        // Indicates the quality with which the restriction and cancellation sign for speeds was recognized with the
        // camera: 0 - 100 / Gibt aus, mit welcher Güte das Beschränkungs- und Aufhebungszeichen für Geschwindigkeiten
        // mit der Kamera erkannt wurde: 0 - 100

// Skipping STEUERN_METHODE_SLI on 0xD3AB which takes arguments

// Skipping EMPFEHLUNG_FLA_STFLA on 0xD3AD which takes arguments

// Skipping SELBST_KALIBRIERUNG on 0xD3BD which takes arguments

// Skipping KAFAS_SCHEIBENHEIZUNG on 0xD3CD which takes arguments

#define I3_PID_KAF_SPANNUNG_KLEMME_15N_WERT                          0xDAD2
        // Voltage value on the control unit at terminal 15N (accurate to one decimal place) / Spannungswert am
        // Steuergerät an Klemme 15N (auf eine Nachkommastelle genau)

    #define I3_RES_KAF_STAT_SPANNUNG_KLEMME_15N_WERT                 (RXBUF_UINT(0)/10.0f)
    #define I3_RES_KAF_STAT_SPANNUNG_KLEMME_15N_WERT_UNIT            'V'
    #define I3_RES_KAF_STAT_SPANNUNG_KLEMME_15N_WERT_TYPE            float
        // Voltage value on the control unit at terminal 15N (accurate to one decimal place) / Spannungswert am
        // Steuergerät an Klemme 15N (auf eine Nachkommastelle genau)

#define I3_PID_KAF__DEBUG_AUSGABE                                    0xF001
        // Debug output for KAFAS / Debug Ausgabe für KAFAS

    #define I3_RES_KAF_STAT_DEBUG_AUSGABE                            (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_DEBUG_AUSGABE_UNIT                       '0-n'
    #define I3_RES_KAF_STAT_DEBUG_AUSGABE_TYPE                       unsigned short
        // Returns the status of whether the debug message output is active / Liefert den Status ob die Ausgabe der
        // Debug-Nachrichten aktiv ist

// Skipping _SIM_COUNTRY_CODE on 0xF002 which takes arguments

#define I3_PID_KAF__PEDANTIC_MODE                                    0xF003
        // Pedantic mode for SLI and NPI / Pedantic Mode für  SLI und NPI

    #define I3_RES_KAF_STAT_PEDANTIC_MODE                            (RXBUF_UCHAR(0))
    #define I3_RES_KAF_STAT_PEDANTIC_MODE_UNIT                       '0-n'
    #define I3_RES_KAF_STAT_PEDANTIC_MODE_TYPE                       unsigned char
        // Activation status of Pedantic Mode for SLI and NPI / Aktivierungsstatus des Pedantic Mode für SLI und NPI

#define I3_PID_KAF__ERASE_MICRO_CORE_DUMP                            0xF004
        // Delete from MicroCoreDump / Löschen vom MicroCoreDump

    #define I3_RES_KAF_STAT_ERASE_RESULT                             (RXBUF_UINT(0))
    #define I3_RES_KAF_STAT_ERASE_RESULT_UNIT                        '0-n'
    #define I3_RES_KAF_STAT_ERASE_RESULT_TYPE                        unsigned short
        // Deletion result / Löschergebnis
