/*
;    Project:       Open Vehicle Monitor System
;    Date:          22th March 2026
;
;    Changes:
;    1.0  Initial release
;
;    (C) 2026       Carsten Schmiemann
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in
; all copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
; THE SOFTWARE.
*/

#include "ovms_webserver.h"

/**
 * HandleMetrics: display all metrics with live updates
 */
void OvmsWebServer::HandleMetrics(PageEntry_t& p, PageContext_t& c)
{
  c.head(200);
  PAGE_HOOK("body.pre");

  c.print(
    "<style>\n"
      "#metrics-table { font-size: 13px; }\n"
      "#metrics-table td { font-family: \"Menlo\", \"Consolas\", \"Liberation Mono\", monospace; }\n"
      "#metrics-table .value-cell { word-break: break-all; }\n"
      "#metrics-table .value-cell.editable { cursor: pointer; }\n"
      "#metrics-table .value-cell.editable[contenteditable=\"true\"] { outline: 2px solid #5cb85c; background-color: #f9fff9; }\n"
      "#metrics-table .value-cell.error { color: #d9534f; font-weight: bold; }\n"
      "#metrics-table .value-cell.updated { background-color: rgba(0,212,255,.25); transition: background-color 0s; }\n"
      "#metrics-table .value-cell.flash { background-color: transparent; transition: background-color .8s ease-out; }\n"
      ".filter-buttons { margin-bottom: 10px; }\n"
      ".filter-buttons .btn { margin-right: 5px; margin-bottom: 5px; }\n"
      ".filter-buttons .btn.active { font-weight: bold; }\n"
      ".dataTables_filter { margin-bottom: 10px; }\n"
    "</style>\n"
    "<div class=\"panel panel-primary panel-single receiver\" id=\"metrics-panel\">\n"
      "<div class=\"panel-heading\">Metrics</div>\n"
      "<div class=\"panel-body\">\n"
        "<div class=\"filter-buttons\">\n"
          "<button type=\"button\" class=\"btn btn-default active\" data-filter=\"\">All</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^v\\.\">Vehicle (v.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^m\\.\">Module (m.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^s\\.\">Server (s.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^x\">Custom (x*)</button>\n"
        "</div>\n"
        "<table id=\"metrics-table\" class=\"table table-striped table-bordered table-condensed\">\n"
          "<thead>\n"
            "<tr>\n"
              "<th>Metric</th>\n"
              "<th>Value</th>\n"
              "<th>Unit</th>\n"
            "</tr>\n"
          "</thead>\n"
          "<tbody>\n"
          "</tbody>\n"
        "</table>\n"
      "</div>\n"
    "</div>\n"
    "<script>\n"
    "(function(){\n"
      "var metricsTable;\n"
      "// Format value for display\n"
      "function formatValue(val) {\n"
        "if (val == null) return '';\n"
        "if (Array.isArray(val)) {\n"
          "if (val.length === 0) return '[]';\n"
          "if (val.length <= 10) return '[' + val.join(', ') + ']';\n"
          "return '[' + val.slice(0, 10).join(', ') + ', ... (' + val.length + ' items)]';\n"
        "}\n"
        "if (typeof val === 'object') return JSON.stringify(val);\n"
        "return String(val);\n"
      "}\n"
      "// Build sorted rows\n"
      "function buildTable() {\n"
        "var rows = [], names = Object.keys(metrics).sort();\n"
        "for (var i = 0; i < names.length; i++) {\n"
          "var n = names[i];\n"
          "rows.push([n, formatValue(metrics[n]), metrics_label[n] || '']);\n"
        "}\n"
        "return rows;\n"
      "}\n"
      "// Init DataTable\n"
      "function initTable() {\n"
        "metricsTable = $('#metrics-table').DataTable({\n"
          "data: buildTable(),\n"
          "columns: [\n"
            "{ title: 'Metric', width: '35%' },\n"
            "{ title: 'Value', width: '50%', className: 'value-cell' },\n"
            "{ title: 'Unit', width: '15%' }\n"
          "],\n"
          "columnDefs: [{ targets: 1, createdCell: function(td) { $(td).addClass('editable'); } }],\n"
          "order: [[0, 'asc']],\n"
          "paging: false,\n"
          "info: false,\n"
          "searching: true,\n"
          "autoWidth: false,\n"
          "responsive: true,\n"
          "language: { search: 'Search:', zeroRecords: 'No matching metrics found' }\n"
        "});\n"
        "$('#metrics-table').data('dataTable', metricsTable).addClass('has-dataTable');\n"
        "bindEditableCells();\n"
      "}\n"
      "// Quote for shell\n"
      "function quoteValue(v) {\n"

        "if (v.indexOf('\"') < 0) return '\"' + v + '\"';\n"
        "return \"'\" + v + \"'\";\n"
      "}\n"
      "// Set metric via shell\n"
      "function setMetricValue(metric, value, $cell) {\n"
        "if (!metric) return;\n"
        "var tv = String(value).trim(), rv = tv;\n"
        "if (typeof(metrics[metric]) != 'string') {\n"
          "try { rv = JSON.parse(tv).toString(); }\n"
          "catch (err) { $cell.addClass('error'); return; }\n"
        "}\n"
        "loadcmd('metrics set ' + metric + ' ' + quoteValue(rv)).then(function(resp) {\n"
          "if (resp && resp.indexOf('Metric set') >= 0) {\n"
            "$cell.removeClass('error');\n"
            "metrics[metric] = rv;\n"
            "var u = {}; u[metric] = metrics[metric];\n"
            "updateMetrics(u);\n"
          "} else {\n"
            "$cell.addClass('error');\n"
          "}\n"
        "}, function() {\n"
          "$cell.addClass('error');\n"
        "});\n"
      "}\n"
      "// Inline editing events\n"
      "function bindEditableCells() {\n"
        "var $tb = $('#metrics-table tbody');\n"
        "// Dblclick to edit\n"
        "$tb.on('dblclick', 'td.value-cell', function() {\n"
          "var $c = $(this);\n"
          "if ($c.attr('contenteditable') === 'true') return;\n"
          "var rd = metricsTable.row($c.closest('tr')).data();\n"
          "if (!rd || !rd.length) return;\n"
          "var ct = $.trim($c.text());\n"
          "if (Array.isArray(metrics[rd[0]])) ct = JSON.stringify(metrics[rd[0]]);\n"
          "$c.text(ct).data('orig-value', ct);\n"
          "$c.attr('contenteditable', 'true').addClass('editing').focus();\n"
          "document.execCommand('selectAll', false, null);\n"
        "});\n"
        "// Enter/Escape handling\n"
        "$tb.on('keydown', 'td.value-cell.editing', function(ev) {\n"
          "if (ev.key === 'Enter') {\n"
            "ev.preventDefault();\n"
            "var $c = $(this), nv = $.trim($c.text()), ov = $c.data('orig-value');\n"
            "var rd = metricsTable.row($c.closest('tr')).data();\n"
            "$c.attr('contenteditable', 'false').removeClass('editing');\n"
            "if (!rd || !rd.length || nv === ov) return;\n"
            "setMetricValue(rd[0], nv, $c);\n"
          "}\n"
          "if (ev.key === 'Escape') {\n"
            "var $c = $(this);\n"
            "$c.text($c.data('orig-value') || '').attr('contenteditable', 'false').removeClass('editing');\n"
          "}\n"
        "});\n"
        "// Cancel on blur\n"
        "$tb.on('blur', 'td.value-cell.editing', function() {\n"
          "var $c = $(this);\n"
          "$c.text($c.data('orig-value') || '').attr('contenteditable', 'false').removeClass('editing');\n"
        "});\n"
      "}\n"
      "// Apply metric updates\n"
      "function updateMetrics(update) {\n"
        "if (!metricsTable) return;\n"
        "var updatedRows = [], existing = {};\n"
        "metricsTable.rows().every(function(rowIdx) {\n"
          "var d = this.data(), n = d[0];\n"
          "existing[n] = true;\n"
          "if (update[n] !== undefined) {\n"
            "var $vcell = $(this.node()).find('.value-cell');\n"
            "// Skip edited cells\n"
            "if ($vcell.hasClass('editing')) {\n"
              "$vcell.data('orig-value', formatValue(metrics[n]));\n"
              "return;\n"
            "}\n"
            "var nv = formatValue(metrics[n]), nu = metrics_label[n] || '';\n"
            "if (d[1] !== nv || d[2] !== nu) {\n"
              "d[1] = nv; d[2] = nu;\n"
              "this.data(d);\n"
              "updatedRows.push(rowIdx);\n"
            "}\n"
          "}\n"
        "});\n"
        "var newRows = [];\n"
        "// Add new metrics\n"
        "for (var n in update) {\n"
          "if (!existing[n]) newRows.push([n, formatValue(metrics[n]), metrics_label[n] || '']);\n"
        "}\n"
        "// Flash updated rows\n"
        "if (newRows.length) metricsTable.rows.add(newRows).draw(false);\n"
        "if (updatedRows.length) {\n"
          "metricsTable.rows(updatedRows).nodes().to$().find('.value-cell')\n"
            ".addClass('updated').each(function() {\n"
              "var el = this;\n"
              "setTimeout(function() {\n"
                "$(el).addClass('flash').removeClass('updated');\n"
                "setTimeout(function() { $(el).removeClass('flash'); }, 500);\n"
              "}, 50);\n"
            "});\n"
        "}\n"
      "}\n"
      "// Filter buttons\n"
      "$('.filter-buttons .btn').on('click', function() {\n"
        "$('.filter-buttons .btn').removeClass('active');\n"
        "$(this).addClass('active');\n"
        "if (metricsTable) metricsTable.column(0).search($(this).data('filter'), true, false).draw();\n"
      "});\n"
      "// Metrics updates\n"
      "$('#metrics-panel').on('msg:metrics', function(e, update) {\n"
        "updateMetrics(update);\n"
      "});\n"
      "// Initialize table\n"
      "if (window.DataTable) {\n"
        "initTable();\n"
      "} else {\n"
        "$.ajax({\n"
          "url: \"" URL_ASSETS_TABLES_JS "\",\n"
          "dataType: \"script\",\n"
          "cache: true,\n"
          "success: function() { initTable(); }\n"
        "});\n"
      "}\n"
    "})();\n"
    "</script>\n");

  PAGE_HOOK("body.post");
  c.done();
}
