/*
;    Project:       Open Vehicle Monitor System
;    Date:          November 2025
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in
; all copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
; THE SOFTWARE.
*/

#include "ovms_webserver.h"

#define _attr(text) (c.encode_html(text).c_str())
#define _html(text) (c.encode_html(text).c_str())

#ifdef CONFIG_OVMS_COMP_OTA
#include "ovms_ota.h"

/**
 * HandleCfgPartitioning: OTA partition upgrade tool (URL /cfg/partitioning)
 */
void OvmsWebServer::HandleCfgPartitioning(PageEntry_t& p, PageContext_t& c)
{
  // UI logic fully on client side:
  c.head(200);
  c.print(
    "<div class=\"panel panel-primary\">\n"
      "<div class=\"panel-heading\">Partitioning Scheme</div>\n"
      "<div class=\"panel-body\">\n"
        "<pre id=\"ota-status\" title=\"OTA Status\">Fetching…</pre>\n"
        "<div id=\"status-info\">\n"
          "<div id=\"type-v3-30\" style=\"display:none\">\n"
            "<div class=\"alert alert-warning\">\n"
              "<p><strong>Your module is running an outdated partitioning scheme.</strong></p>\n"
              "<p>We recommend upgrading your partitioning scheme to support firmware updates larger than 4MB in size.</p>\n"
            "</div>\n"
            "<p>The upgrade procedure runs <strong>fully automatic</strong>, you just need to start it. Depending on your\n"
              "configuration, the upgrade can take <strong>up to 10 minutes</strong> to finish, so please be patient.</p>\n"
            "<p>In case something goes wrong, the module will reboot into standard mode, and you can use this page to\n"
              "display and download the upgrade log for further analysis.</p>\n"
            "<p><u>Note</u>: in case something goes <em>badly</em> wrong, you may need to reinstall the module via USB.\n"
              "See <a href=\"https://docs.openvehicles.com/en/latest/userguide/factory.html#full-reflash-via-usb\"\n"
                "target=\"_blank\">user guide</a> on how to do this.</p>\n"
            "<p>We <strong>strongly recommend</strong> creating a config backup first in case you haven't done already:\n"
              "<a class=\"btn btn-default\" href=\"/cfg/backup\" target=\"#main\">Configuration Backup</a></p>\n"
            "<p>\n"
              "<button type=\"button\" class=\"btn btn-primary\" data-action=\"upgrade\">Start partition upgrade now</button>\n"
            "</p>\n"
          "</div>\n"
          "<div id=\"type-v3-34\" style=\"display:none\">\n"
            "<div class=\"alert alert-danger\">\n"
              "<p>The upgrade process has <strong>failed to finish the store migration</strong>, most likely caused by\n"
                "a config filesystem corruption. Please check the upgrade log for details.</p>\n"
              "<p>We recommend doing a <strong>factory reset</strong> (erasing &amp; reformatting the config store) now\n"
                "to get a clean state. The upgrade procedure will continue automatically after the reboot.</p>\n"
            "</div>\n"
            "<p>\n"
              "<button type=\"button\" class=\"btn btn-primary\" data-action=\"factory-reset\">Perform factory reset now</button>\n"
              "<button type=\"button\" class=\"btn btn-primary\" data-action=\"upgrade\">Continue/retry partition upgrade</button>\n"
            "</p>\n"
            "<p><u>Note</u>: after the factory reset, the module will reboot into the initial setup mode (with Wifi\n"
              "network <code>OVMS</code>). You can then restore your config backup if available, or reconfigure\n"
              "the module from scratch.</p>\n"
          "</div>\n"
          "<div id=\"type-v3-35\" style=\"display:none\">\n"
            "<div class=\"alert alert-success\">\n"
              "<p id=\"upgrade-success\" style=\"display:none\">\n"
                "<strong>The partition upgrade process has finished successfully:</strong>\n"
              "</p>\n"
              "<p><strong>The partitioning scheme is up to date.</strong></p>\n"
            "</div>\n"
          "</div>\n"
          "<div id=\"type-unknown\" style=\"display:none\">\n"
            "<div class=\"alert alert-warning\">\n"
              "<p><strong>The partitioning scheme cannot be determined or is not supported.</strong></p>\n"
              "<p>Please verify your firmware is up to date.</p>\n"
            "</div>\n"
          "</div>\n"
        "</div>\n"
        "<div id=\"upgrade-log\" style=\"display:none\">\n"
          "<p>The partition upgrade has logged <span id=\"errcnt\">0</span> error(s) and <span id=\"warncnt\">0</span> warning(s).</p>\n"
          "<p>\n"
            "<button type=\"button\" class=\"btn btn-default\" data-action=\"showlog\">Display upgrade log</button>\n"
            "<button type=\"button\" class=\"btn btn-default\" data-action=\"deletelog\">Delete upgrade log</button>\n"
          "</p>\n"
        "</div>\n"
      "</div>\n"
      "<div class=\"modal fade\" id=\"op-dialog\" role=\"dialog\" data-backdrop=\"static\" data-keyboard=\"false\">\n"
        "<div class=\"modal-dialog modal-lg\">\n"
          "<div class=\"modal-content\">\n"
            "<div class=\"modal-header\">\n"
              "<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
              "<h4 class=\"modal-title\" id=\"op-title\"></h4>\n"
            "</div>\n"
            "<div class=\"modal-body\">\n"
              "<pre id=\"op-output\"></pre>\n"
              "<div id=\"op-upgrading\" style=\"display:none\">\n"
                "<div class=\"alert alert-info\">\n"
                  "<p><strong>The upgrade is running now, estimated run time: up to <span id=\"op-runtime\">?</span> minutes</strong></p>\n"
                  "<p>Keep this page open until the process has finished.</p>\n"
                  "<p>After the upgrade has finished, the browser will automatically reconnect to the module.\n"
                    "If the reconnect fails with a browser error, wait a bit, then reload the page manually.\n"
                    "You will need to login, this page will then show the upgrade result and log.</p>\n"
                  "<p class=\"info-factoryreset\" style=\"display:none\">\n"
                    "<strong><u>Important</u>:</strong> due to the factory reset, the module will boot into the initial\n"
                    "setup mode. Open your Wifi network monitor now, and connect to the <code>OVMS</code> Wifi\n"
                    "network as soon as available, using the setup password <code>OVMSinit</code>.\n"
                  "</p>\n"
                "</div>\n"
                "<div class=\"progress\">\n"
                  "<div id=\"op-progress\" class=\"progress-bar progress-bar-striped active\" role=\"progressbar\"\n"
                    "aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width:0%\">0%</div>\n"
                "</div>\n"
                "<div class=\"alert alert-danger danger-poweroff\">\n"
                  "<p><strong>Do not power off the module while the upgrade is running!</strong></p>\n"
                "</div>\n"
                "<div class=\"alert alert-warning warning-stuck\" style=\"display:none\">\n"
                  "<p><strong>The expected upgrade time has passed.</strong></p>\n"
                  "<p>Give the module another minute or two and try reloading this page manually. If the module\n"
                    "remains unresponsive, unplug &amp; replug the module.</p>\n"
                  "<p>If the module then still doesn't come back online\n"
                    "<span class=\"info-factoryreset\" style=\"display:none\">(with the initial <code>OVMS</code>\n"
                    "Wifi network)</span> you will need to\n"
                    "<a href=\"https://docs.openvehicles.com/en/latest/userguide/factory.html#full-reflash-via-usb\"\n"
                    "target=\"_blank\">reflash the module via USB</a>.</p>\n"
                  "<p><strong>Sorry for the inconvenience!</strong></p>\n"
                "</div>\n"
              "</div>\n"
            "</div>\n"
            "<div class=\"modal-footer\">\n"
              "<button type=\"button\" class=\"btn btn-default\" data-download=\"#op-output\" data-filename=\"#op-title\">Download</button>\n"
              "<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"
            "</div>\n"
          "</div>\n"
        "</div>\n"
      "</div>\n"
    "</div>\n"
    "<style>\n"
    "#op-output {\n"
      "overflow: auto;\n"
      "max-height: calc(100vh - 230px);\n"
    "}\n"
    "</style>\n"
    "<script>\n"
    "(function(){\n"
      "const $modal = $(\"#op-dialog\"), $title = $(\"#op-title\"), $output = $(\"#op-output\"), $progress = $(\"#op-progress\");\n"
      "var status = {};\n"
      "// Init:\n"
      "loadcmd(\"ota\", \"#ota-status\").then((output) => {\n"
        "// Scan result:\n"
        "status.parttype = (output.match(/Partition type:\\s*(\\S*)/)||[])[1];\n"
        "status.bootpart = (output.match(/Boot partition:\\s*(\\S*)/)||[])[1];\n"
        "// Show partition type info:\n"
        "let $ti = $(`#type-${status.parttype}`);\n"
        "if ($ti.length == 0) $ti = $(\"#type-unknown\");\n"
        "$ti.show();\n"
        "// Get upgrade log:\n"
        "loadcmd(\"vfs cat /store/partition-update.log\").then((output) => {\n"
          "status.upgradelog = output;\n"
          "if (output != \"\" && !output.startsWith(\"Error: VFS\")) {\n"
            "let errs = output.match(/error:/gi)||[], warns = output.match(/warning:/gi)||[];\n"
            "$(\"#errcnt\").text(errs.length);\n"
            "$(\"#warncnt\").text(warns.length);\n"
            "$(\"#upgrade-log\").show();\n"
            "$(\"#upgrade-success\").show();\n"
          "}\n"
        "});\n"
      "});\n"
      "// Dialog utils:\n"
      "function showDialog(opt) {\n"
        "$modal.find(\"button[data-dismiss]\").toggle(!!opt.closable);\n"
        "$modal.find(\"button[data-download]\").toggle(!!opt.downloadable);\n"
        "$output.toggleClass(\"loading\", !opt.closable);\n"
        "$modal.modal(\"show\");\n"
      "}\n"
      "function startProgressBar() {\n"
        "// estimate upgrade run time from here:\n"
        "const tm = { \"reboot\": 60, \"pcopy\": 30, \"ptable\": 15, \"migrate\": 60, \"reconnect\": 30 };\n"
        "let time_expected, time_elapsed;\n"
        "if (status.parttype == \"v3-30\") {\n"
          "if (status.bootpart != \"factory\")\n"
            "time_expected = tm.pcopy + tm.ptable + tm.migrate + 4*tm.reboot + tm.reconnect;\n"
          "else\n"
            "time_expected = tm.ptable + tm.migrate + 3*tm.reboot + tm.reconnect;\n"
        "}\n"
        "else if (status.parttype == \"v3-34\") {\n"
          "time_expected = tm.migrate + 2*tm.reboot + tm.reconnect;\n"
        "}\n"
        "else {\n"
          "time_expected = tm.reboot + tm.reconnect;\n"
        "}\n"
        "if (status.factoryreset) {\n"
          "time_expected -= tm.migrate;\n"
          "time_expected += 5;\n"
        "}\n"
        "// display upgrade progress info:\n"
        "$modal.find(\".info-factoryreset\").toggle(!!status.factoryreset);\n"
        "$modal.find(\"#op-runtime\").text(Math.ceil(time_expected/60));\n"
        "$modal.find(\"#op-upgrading\").show();\n"
        "status.upgrading = true;\n"
        "time_elapsed = 0;\n"
        "// close connection:\n"
        "if (ws) {\n"
          "ws_inhibit = tm.reboot;\n"
          "ws.close();\n"
        "}\n"
        "window.setInterval(() => {\n"
          "time_elapsed += 1;\n"
          "// update progress state:\n"
          "let prc = Number((time_elapsed / time_expected) * 100).toFixed(0);\n"
          "if (prc > 100) {\n"
            "prc = 100;\n"
            "$progress.addClass(\"progress-bar-warning\");\n"
            "$modal.find(\".danger-poweroff\").hide();\n"
            "$modal.find(\".warning-stuck\").show();\n"
          "}\n"
          "$progress.css(\"width\", prc+\"%\").attr(\"aria-valuenow\", prc).text(`${prc}%`);\n"
          "// connection reestablished?\n"
          "if (ws && ws.readyState == ws.OPEN) {\n"
            "location.reload();\n"
          "}\n"
        "}, 1000);\n"
      "}\n"
      "// Actions:\n"
      "$(\"button[data-action]\").on(\"click\", function (ev) {\n"
        "function msgfilter(msg) {\n"
          "if (msg.text && msg.text.indexOf(\"Factory reset of configuration store complete\") >= 0)\n"
            "status.factoryreset = true;\n"
          "if (msg.error && msg.request.status < 400)\n"
            "return null; // suppress timeout/abort errors\n"
          "else if (msg.text && msg.text.indexOf(\"upgrade is running\") >= 0)\n"
            "startProgressBar();\n"
          "return standardTextFilter(msg);\n"
        "}\n"
        "let action = $(this).data(\"action\"), cmd, desc;\n"
        "status.upgrading = false;\n"
        "switch (action) {\n"
          "case \"showlog\":\n"
            "$title.text(\"Partition upgrade\");\n"
            "$output.text(status.upgradelog);\n"
            "showDialog({ \"closable\": true, \"downloadable\": true });\n"
            "break;\n"
          "case \"deletelog\":\n"
            "desc = \"Log cleanup\";\n"
            "cmd = \"vfs rm /store/partition-update.log\";\n"
            "break;\n"
          "case \"upgrade\":\n"
            "desc = \"Partition upgrade\";\n"
            "cmd = \"ota partitions upgrade autocont -noconfirm\";\n"
            "break;\n"
          "case \"factory-reset\":\n"
            "desc = \"Factory reset &amp; retry upgrade\";\n"
            "cmd = \"module factory reset -noconfirm\";\n"
            "break;\n"
        "}\n"
        "if (cmd) {\n"
          "confirmdialog(\"Please confirm\", `Execute ${desc.toLowerCase()}?`, [\"Cancel\", \"OK\"], function(ok) {\n"
            "if (ok) {\n"
              "$title.text(desc);\n"
              "$output.text(\"\");\n"
              "showDialog({ \"closable\": false });\n"
              "loadcmd(cmd, $output, msgfilter).then((res) => {\n"
                "showDialog({ \"closable\": !status.upgrading });\n"
                "// UI bookkeeping:\n"
                "switch (action) {\n"
                  "case \"deletelog\":\n"
                    "status.upgradelog = \"\";\n"
                    "$(\"#upgrade-log\").hide();\n"
                    "break;\n"
                "}\n"
              "});\n"
            "}\n"
          "});\n"
        "}\n"
      "});\n"
      "// Download:\n"
      "$(\"button[data-download]\").on(\"click\", function (ev) {\n"
        "let fn = $($(this).data(\"filename\")).text().replaceAll(\" \",\"-\")||\"Log\",\n"
          "text = $($(this).data(\"download\")).text(),\n"
          "data = \"data:text/plain;charset=utf-8,\" + encodeURIComponent(text);\n"
        "let $a = $(`<a class=\"hidden\" download=\"${fn}.txt\" href=\"${data}\" />`);\n"
        "$a.insertAfter($(this)).get(0).click();\n"
        "$a.remove();\n"
      "});\n"
    "})()\n"
    "</script>\n"
  );
  c.done();
}
#endif // CONFIG_OVMS_COMP_OTA
