#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ovms3

# Not compatible with ESP-IDF < 4
EXCLUDE_COMPONENTS := esp_wireguard

include $(IDF_PATH)/make/project.mk
