---
name: 'CI Fallback'

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  documentation:
    runs-on: 'ubuntu-22.04'

    steps:
      - run: 'echo "No build required"'
